export const IMAGE_INITIAL_LOAD = "IMAGE_INITIAL_LOAD";
export const IMAGE_INITIAL_LOAD_FAILED = "IMAGE_INITIAL_LOAD_FAILED";
export const IMAGE_SEARCH_LOAD = "IMAGE_SEARCH_LOAD";
export const IMAGE_SEARCH_LOAD_FAILED = "IMAGE_SEARCH_LOAD_FAILED";
